# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f39d87c4fdbafefec54da17c6b335364706c5ee2aaf4b16a6582c2e94639c0417cd0f61a216ca2665c85a76fa04c75a8b4eb612ba0c307c641d8a9f486b88b

test:
  secret_key_base: 1355dac4d2486a22d9a707b16af560bd65d7fd9cd6e35ba257b8dcf1ead832e8411528d07aa6197b60d68b65a9b44e6d299dc0a36d374530ea88122c49bac04c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
